nelmio_api_doc:
    documentation:
        info:
            title: URL shortener
            description: Internal API for the URL Shortener
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
    models: { use_jms: false }