version: '3'

services:
    database:
        image: mysql:8.0
        platform: linux/arm64/v8
        ports: [3306]
        command: --sort_buffer_size=512K
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: admin
            MYSQL_PASSWORD: dev
            MYSQL_DATABASE: urlshortener